### ISSUE TITLE
Label not visible in IDE

### ISSUE THREAD

**Issue by MisterBruno** [devtimi/BootstrapWebButton#1]
I suggest we bring back the regular "caption" property instead of having a label, simply to better visualise the button name in the IDE.

**Comment by devtimi** [comment]
I tried to keep that design, but I was unable to get it to work. Overriding Caption, I wasn't able to set the actual WebButton's caption. If you are able to do so, feel free to make a pull request!

**Comment by MisterBruno** [comment]
Will do. I was able to do it in the original design so I'll try to bring it back in.
