### ISSUE TITLE
Text alignment on horizontal buttons

### ISSUE THREAD

**Issue by MisterBruno** [devtimi/BootstrapWebButton#3]
The button is currently always centered. When creating buttons with an icon and text in a horizontal arrangement, it would be useful to have a text alignment property. This would allow, for example, to create buttons for a vertical navigation bar. I already have worked on this so I will implement it.

**Comment by devtimi** [comment]
I've merged this change and also updated it to use the Xojo Framework `TextAlignments` enumeration :)

**Comment by MisterBruno** [comment]
Great, thanks a lot. As a padawan, I appreciate your Jedi insight :-)
